import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Image from "next/image";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  title: "Vissasa",
  description: "Generated by create next app",
};

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="layout">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
